In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['Col1','Col2','Col3','Col4'])

In [3]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [4]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [5]:
df.to_csv('Test1.csv')

In [6]:
df2 = pd.DataFrame([[10,20,30,40], [1,2,3,4], [2,4,6,8], [2,4,6,8], [10,20,30,40]], index=['Row1','Row2','Row3','Row4','Row5'], columns=['Col1','Col2','Col3','Col4'])
df2

      Col1  Col2  Col3  Col4
Row1    10    20    30    40
Row2     1     2     3     4
Row3     2     4     6     8
Row4     2     4     6     8
Row5    10    20    30    40

In [7]:
df2.to_json('Test2.json')
df2.to_html('Test2.html')

In [8]:
df2.to_xml('Test2.xml')

In [9]:
# df.loc['Row1']
# df.loc['Row1':'Row3']
# type(df.loc['Row1'])
# type(df.loc['Row1':'Row3'])

# loc is a method in pandas that allows you to access a group of rows and columns by labels or a boolean array. When you use loc with a single label, it returns a Series object representing the row. When you use loc with a range of labels, it returns a DataFrame object containing the specified rows.

# So basically, in Python DataSeries and Dataframe are two different data structures. A DataSeries is a one-dimensional array-like object that can hold any data type, while a DataFrame is a two-dimensional table-like structure that consists of rows and columns.

In [10]:
# iloc is a method in pandas that allows you to access a group of rows and columns by integer position. When you use iloc with a single integer, it returns a Series object representing the row at that position. When you use iloc with a range of integers, it returns a DataFrame object containing the specified rows.

# df.iloc[0]
# df.iloc[0:3]
# df.iloc[0,0]
# df.iloc[0:3, 0:2] # same like numpy slicing

In [11]:
df.iloc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [12]:
df.iloc[:2,:2]

type(df.iloc[:2,:2])   #In Python indexing, [a:b,c:d] a in inclusive and b in exclusive.

pandas.DataFrame

In [13]:
df.iloc[0:2,0]

Row1    0
Row2    4
Name: Col1, dtype: int64

In [14]:
df.iloc[:,1:]

      Col2  Col3  Col4
Row1     1     2     3
Row2     5     6     7
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [15]:
#Convert dataframe to numpy array
# df.values
df.iloc[:,1:].values.shape

(5, 3)

In [16]:
df['Col1'].value_counts()

Col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [17]:
df.isnull().sum() # to check how many null values are there in each column.

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [18]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [19]:
df[['Col1','Col2']]

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

In [20]:
df3 =pd.read_csv('C:\\Users\\suhai\\Downloads\\Krish Naik Youtube Python\\mercedesbenz.csv')

# By default the read_csv file has a , as a separator - but if your file has a different separator like ; etc you can specify the same during the defining and mention a parameter sep=';' etc.

## something like - test_df = pd.read_csv('test1.csv', sep =';')

In [21]:
df3.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [23]:
df3.describe() #only integers and float values are considered for describe method. Object type is not considered. It will give you count, mean, std, min, 25%, 50%, 75% and max values for each column.

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
#Get unique category counts
df3['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [25]:
df3[df3['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [26]:
from io import StringIO, BytesIO #StringIO is used to read and write strings as files. It is a class in the io module that provides a file-like interface for working with strings. You can use StringIO to create an in-memory file object that can be read from or written to like a regular file.

In [27]:
data = ("col1,col2,col3\n"
        "x,y,1\n"
        "a,b,2\n"
        "c,d,3")

In [28]:
type(data)

str

In [29]:
StringIO(data)

In [30]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [31]:
tdf=pd.read_csv(StringIO(data), usecols=['col1','col3']) #using only specific columns by using usecols parameter.

In [32]:
tdf.to_csv('Test3.csv')
tdf

  col1  col3
0    x     1
1    a     2
2    c     3

In [33]:
## Specifying column data types
data2 = ("col1,col2,col3\n"
        "x,y,1\n"
        "a,b,2\n"
        "c,d,3")

In [34]:
print(data2)

col1,col2,col3
x,y,1
a,b,2
c,d,3

In [35]:
df4 = pd.read_csv(StringIO(data2), dtype={'col1':str, 'col2':str, 'col3':int})

type(df4['col2'])

pandas.Series

In [36]:
df4.dtypes

col1      str
col2      str
col3    int64
dtype: object

In [37]:
df4['col1'][2]

'c'

In [38]:
type(df4['col1'][2])

str

In [39]:
data3 = ("index,a,b,c\n"
         "4, apple, bat, 5.7\n"
         "8, orange, cow, 10")

In [40]:
pd.read_csv(StringIO(data3), index_col=0)

             a     b     c
index
4        apple   bat   5.7
8       orange   cow  10.0

# index_col parameter is used to specify which column to use as the index of the DataFrame. In this case, we are using the first column (index) as the index of the DataFrame (here 4,8). if it wasn't used then by default, there would have been an index 0, 1 .... so on

In [41]:
# Combining usecols and index_col
pd.read_csv(StringIO(data3), usecols=["b","c"], index_col=False)

      b     c
0   bat   5.7
1   cow  10.0

In [42]:
# Quoting and Escape Characters. Very useful in NLP

In [43]:
data5 = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [44]:
pd.read_csv(StringIO(data5), escapechar='\\')

                               a  b
0  hello, "Bob", nice to see you  5

# URL to CSV

In [46]:
import pandas as pd
import requests
from io import StringIO

url = "https://download.bls.gov/pub/time.series/cu/cu.item"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Connection": "keep-alive"
}

response = requests.get(url, headers=headers)

print(response.status_code)

df5 = pd.read_csv(StringIO(response.text), sep="\t")
df5.head()

200

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359